version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWSACOUNT.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t $REPO:$TAG .
      - docker tag $REPO:$TAG $AWSACOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO:$TAG
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Between life and death 9
      - echo Pushing the Docker image...
      - docker push $AWSACOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO:$TAG
