version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password 
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t test-ecr:0.0.1 .
      - docker tag 
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 
